In [25]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [36]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x,y = load_breast_cancer(return_X_y=True)

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [30]:
lr = LogisticRegression()

In [31]:
lr.fit(x_train,y_train)
y_pred1 = lr.predict(x_test)
accuracy_score(y_test,y_pred1)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.956140350877193

In [32]:
dc = DecisionTreeClassifier()

In [33]:
dc.fit(x_train,y_train)
y_pred2 = dc.predict(x_test)
accuracy_score(y_test,y_pred2)

0.9385964912280702

In [34]:
confusion_matrix(y_test,y_pred1)


array([[39,  4],
       [ 1, 70]])

In [35]:
confusion_matrix(y_test,y_pred2)

array([[39,  4],
       [ 3, 68]])

In [38]:
print("for Logistic Regression Model")
print("-"*40)
cfd = pd.DataFrame(confusion_matrix(y_test,y_pred1), columns=["Predicted Negative","Predicted Positive"])
print(cfd)
# print(f"Confusion Matrix: \n{confusion_matrix(y_test,y_pred1)}")
print(f"Accuracy Score: {accuracy_score(y_test,y_pred1)}")
print(f"Recall score: {recall_score(y_test,y_pred1)}")
print(f"Precision Score: {precision_score(y_test,y_pred1)}")
print(f"F1 Score: {f1_score(y_test,y_pred1)}")

for Logistic Regression Model
----------------------------------------
   Predicted Negative  Predicted Positive
0                  39                   4
1                   1                  70
Accuracy Score: 0.956140350877193
Recall score: 0.9859154929577465
Precision Score: 0.9459459459459459
F1 Score: 0.9655172413793104


In [39]:
print("for Decision Tree Regression Model")
print("-"*40)
cfd = pd.DataFrame(confusion_matrix(y_test,y_pred2), columns=["Predicted Negative","Predicted Positive"])
print(cfd)
# print(f"Confusion Matrix: \n{confusion_matrix(y_test,y_pred1)}")
print(f"Accuracy Score: {accuracy_score(y_test,y_pred2)}")
print(f"Recall score: {recall_score(y_test,y_pred2)}")
print(f"Precision Score: {precision_score(y_test,y_pred2)}")
print(f"F1 Score: {f1_score(y_test,y_pred2)}")

for Decision Tree Regression Model
----------------------------------------
   Predicted Negative  Predicted Positive
0                  39                   4
1                   3                  68
Accuracy Score: 0.9385964912280702
Recall score: 0.9577464788732394
Precision Score: 0.9444444444444444
F1 Score: 0.951048951048951


In [40]:
precision_score(y_test,y_pred1, average=None)

array([0.975     , 0.94594595])

In [44]:
precision_score(y_test,y_pred1)

0.9459459459459459

In [42]:
precision_score(y_test, y_pred1, average='macro')

0.960472972972973

In [46]:
precision_score(y_test, y_pred1, average='weighted')

0.9569049312470365

In [48]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

